#Headless browser option
browser:
  webkit: "phantomjs"
  gecko: "slimerjs"

#If you want to have multiple snapping files, set the file name here
snap_file: "test/snap.js"

# Type the name of the directory that shots will be stored in
directory:
  - 'shots'

# Add only 2 domains, key will act as a label
domains:
  kitecss: "http://localhost:8000"

#Type screen widths below, here are a couple of examples
screen_widths:
  - 320
  - 600
  - 768
  - 1024
  - 1280

#Type page URL paths below, here are a couple of examples
paths:
  fixed: /test/fixed
  fluid: /test/fluid

#Amount of fuzz ImageMagick will use
fuzz: '20%'

#Set the number of days to keep the site spider file
spider_days:
  - 10
